# Generated by Django 5.0.4 on 2024-04-17 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asclist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asc',
            name='address_primary',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
