# Generated by Django 5.0.4 on 2024-04-17 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asclist', '0002_alter_asc_address_primary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asc',
            name='address_primary',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
