# Generated by Django 5.0.4 on 2024-04-17 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asclist', '0003_alter_asc_address_primary'),
    ]

    operations = [
        migrations.AddField(
            model_name='asc',
            name='city',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='asc',
            name='email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
